---
title: "nba_data"
output:
  html_document: default
---

```{r }
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
mydata <-  read.csv("nba.csv")
```



# 單變數：類別型
```{r }

mydata0 <- mydata[1:8,1:23]

ggplot(mydata0, aes(reorder(PLAYER, GP), GP)) + geom_bar(stat = "identity",fill = "red") + coord_flip()                                                                         
```

# 單變數：連續型
```{r }

mydata1 <- mydata[1:30,1:23]
ggplot(mydata1, aes(PLAYER, REB)) + geom_histogram(stat = "identity",fill = "green") + coord_flip()                                                            
```

# 雙變數：連續 vs 連續
```{r}

mydata2 <- mydata[1:100,1:23]
ggplot(mydata2, aes(MIN, PTS )) + geom_point(stat = "identity", color = "blue")                                                                       
```

# 雙變數：離散 vs 連續
```{r }

mydata3 <- mydata[1:100,1:23]
ggplot(mydata3, aes(TEAM, AST)) + geom_boxplot()+coord_flip()                                                                         
```


